In [1]:
import pandas as pd

sheet= pd.read_excel("cycle_analysis.xlsx", sheetname=2)

D:\python3\lib\site-packages\pandas\io\excel.py:329: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  **kwds)


In [2]:
sheet

SMB       RMW       HML       CMA     CRMHL      AMLH     Rm-Rf  \
0   0.167783 -0.220386 -0.007463  0.085955  0.624381  0.039835  0.165350   
1  -0.440995  0.293465 -0.442516 -0.116459  0.723677  0.006210  0.167199   
2  -0.112024  0.029065 -0.173348 -0.087241  0.678151 -0.022897  0.439081   
3   0.025919  0.064774 -0.145316 -0.057795  0.331387 -0.027173 -0.086180   
4   0.051806 -0.037522 -0.047662 -0.008787  0.339962  0.003491 -0.352628   
5  -0.133694  0.135580 -0.175769 -0.021290  0.303845 -0.049341 -0.189361   
6  -0.054624  0.018319 -0.050053 -0.007020  0.289436  0.014755 -0.145823   
7   0.045438  0.043528 -0.119862 -0.038086  0.344479 -0.035965 -0.170846   
8   0.020938 -0.100433 -0.061002 -0.011722  0.500534  0.086528  0.258473   
9  -0.003702 -0.006652 -0.114928 -0.017647  0.454345  0.043502  0.225895   
10 -0.063052  0.061571 -0.122674 -0.007772  0.360866 -0.084505 -0.080151   
11  0.049767  0.016262 -0.072586 -0.012310  0.347105 -0.088863  0.121005   
12  0.077710 -0.038246 -0.097915  0.003999  0.293410  0.034356 -0.046289   
13 -0.083498  0.100918 -0.154012 -0.011520  0.291292 -0.065463 -0.243252   
14 -0.002037  0.014073 -0.176624  0.012182  0.394881 -0.086835  0.112424   
15 -0.078209  0.086226 -0.114411 -0.014321  0.393435 -0.044916  0.017390   
16  0.026929 -0.064967  0.000833  0.007282  0.294293  0.030707  0.014660   
17 -0.023446  0.040028 -0.054314  0.004399  0.242479 -0.006334 -0.081090   
18 -0.027429  0.025748 -0.081087 -0.006688  0.233228 -0.012393 -0.159453   
19 -0.119701  0.103027 -0.023367 -0.058465  0.262640  0.002817 -0.075991   
20 -0.007434 -0.015211 -0.030878 -0.015931  0.222512  0.025259  0.029837   
21 -0.029015  0.076325 -0.092200 -0.038285  0.295824  0.018809 -0.044524   
22 -0.004594  0.020089 -0.079101 -0.010474  0.249840 -0.016736 -0.072167   
23 -0.061564  0.041174  0.030703  0.002233  0.257850  0.058797  0.084418   
24  0.008625  0.014056 -0.151084 -0.000226  0.361021 -0.032709 -0.027452   
25 -0.078962  0.086778 -0.146848 -0.027777  0.312014 -0.015015 -0.124910   
26 -0.009230 -0.031358 -0.166608  0.024246  0.406546 -0.016705  0.078192   
27 -0.018971  0.035531 -0.023265 -0.002802  0.243912 -0.025058 -0.049642   
28  0.057018 -0.049918 -0.074000  0.005882  0.267681 -0.004306 -0.049963   
29 -0.006660 -0.005052 -0.078302  0.021947  0.234601 -0.023000 -0.012526   
30  0.090822 -0.132891 -0.058619  0.074939  0.344506  0.042071  0.141184   
31 -0.300783  0.105803  0.122712 -0.048449  0.557799  0.112256  0.346311   
32  0.039415 -0.020619 -0.279322  0.020438  0.414843 -0.058820  0.106305   
33 -0.025941 -0.018982 -0.278731  0.057635  0.611695 -0.020967  0.113376   
34 -0.073449  0.057359 -0.106677 -0.015883  0.279128 -0.020353 -0.254753   
35  0.150861 -0.069047 -0.256962 -0.009087  0.526629  0.034369  0.118221   
36 -0.039031  0.018158 -0.019611 -0.029400  0.192068 -0.023206 -0.096074   
37  0.003737  0.044094 -0.074580  0.000298  0.260342 -0.035749 -0.033829   
38  0.001851  0.010411  0.004020 -0.005973  0.274964  0.017987  0.017549   
39  0.028734 -0.050726 -0.036018  0.042454  0.268201  0.005736  0.010792   
40 -0.090058  0.050524  0.036238 -0.040779  0.243838 -0.031764  0.017485   
41 -0.188303  0.157447 -0.014210 -0.051352  0.301568 -0.040533 -0.034986   
42 -0.062617  0.049773 -0.040324 -0.033625  0.295584 -0.043069  0.037036   
43 -0.151461  0.112322 -0.055023 -0.044008  0.264098 -0.023051 -0.031388   
44 -0.058795  0.055116 -0.048740 -0.042067  0.220103 -0.016804 -0.065334   
45 -0.145957  0.156925 -0.078070 -0.018726  0.280151 -0.088940 -0.110308   
46 -0.026864  0.035563  0.003760  0.001164  0.278450 -0.006727  0.008719   

        DSMB      DRMW      DHML      DCMA    DCRMHL     DAMLH    DRm-Rf  
0   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
1  -0.608777  0.513851 -0.435053 -0.202415  0.099295 -0.033625  0.001849  
2   0.328971 -0.264400  0.269168  0.029218 -0.045526 -0.029107  0.271882  
3   0.137943  0.035709  0.028033  0.029446 -0.346764 -0.0042

In [3]:
x=sheet.values
print(x.shape)

(47, 14)


In [4]:
import numpy as np
import random

def estimate_factor(factor,F0,F0_grow):    #only can apply to SMB, RMW, CMA 
    
    if factor=="SMB":
        Range=0.477027
        threshold0=75
        threshold1=81
    if factor=="RMW":
        Range=0.583761
        threshold0=90
        threshold1=83
    if factor=="CMA":
        Range=0.322870
        threshold0=81
        threshold1=67
        
    if F0_grow>0 or F0_grow==0:
        threshold=threshold0
    else:
        threshold=threshold1
    y=range(1,100,1)
    #random.seed(1)
    number=random.sample(y,1)
    
    threshold=[threshold]
    
    if number<threshold or number==threshold:
        if F0_grow>0:
            direction=-1
        else:
            direction=1
    else:
        if F0_grow>0:
            direction=1
        else:
            direction=-1
    F1=F0+F0*Range*direction     
    return (F1)

def direction(factor,F0,F0_grow):    #only can apply to SMB, RMW, CMA 
    
    if factor=="SMB":
        Range=0.477027
        threshold0=75
        threshold1=81
    if factor=="RMW":
        Range=0.583761
        threshold0=90
        threshold1=83
    if factor=="CMA":
        Range=0.322870
        threshold0=81
        threshold1=67
        
    if F0_grow>0 or F0_grow==0:
        threshold=threshold0
    else:
        threshold=threshold1
    y=range(1,100,1)
    #random.seed(1)
    number=random.sample(y,1)
    
    threshold=[threshold]
    
    if number<threshold or number==threshold:
        if F0_grow>0:
            direction=-1
        else:
            direction=1
    else:
        if F0_grow>0:
            direction=1
        else:
            direction=-1
    F1=F0+F0*Range*direction     
    return (direction)

def accuracy(gama):      
    u=0
    l=0
    while u<1000:

        SMB0=x[1:47,0]   
        SMB1=x[2:47,0]  #actual SMB1
        DSMB=x[1:47,7]
        E=np.array([0])
        F=np.array([0])

        for i in range(0,46):
            F0=float(SMB0[i])
            F0_grow=float(DSMB[i])
            Estimated_SMB=estimate_factor("SMB",F0,F0_grow)
            Estimated_direction=direction("SMB",F0,F0_grow)


            E=np.row_stack((E, [Estimated_SMB]))
            F=np.row_stack((F, [Estimated_direction]))
        #print("Estimated_SMB=",E[1:46,:])



        together=np.column_stack((E[1:46,:], SMB1,F[1:46,:],x[1:46,0]))
        #print(together)

        h=0
        hg=0
        for j in range(0,45):
            T=together[j][0]*together[j][1]
            TT=together[j][2]*together[j][3]
            if TT>0 or abs(together[j][0])>gama:
                hg=hg+1
                if T>0:
                    h=h+1

        accuracy=h/hg
        #print(accuracy)
        l=l+accuracy
        u=u+1

    mean_acciracy=l/1000

    return(mean_acciracy)

def trade_time(gama):      
    u=0
    l=0
    while u<1000:

        SMB0=x[1:47,0]   
        SMB1=x[2:47,0]  #actual SMB1
        DSMB=x[1:47,7]
        E=np.array([0])
        F=np.array([0])

        for i in range(0,46):
            F0=float(SMB0[i])
            F0_grow=float(DSMB[i])
            Estimated_SMB=estimate_factor("SMB",F0,F0_grow)
            Estimated_direction=direction("SMB",F0,F0_grow)


            E=np.row_stack((E, [Estimated_SMB]))
            F=np.row_stack((F, [Estimated_direction]))
        #print("Estimated_SMB=",E[1:46,:])



        together=np.column_stack((E[1:46,:], SMB1,F[1:46,:],x[1:46,0]))
        #print(together)

        h=0
        hg=0
        for j in range(0,45):
            T=together[j][0]*together[j][1]
            TT=together[j][2]*together[j][3]
            if TT>0 or abs(together[j][0])>gama:
                hg=hg+1
                if T>0:
                    h=h+1

        #accuracy=h/hg
        #print(accuracy)
        l=l+hg
        u=u+1

    mean_hg=l/1000

    return(mean_hg)

z=np.array([0])
v=np.array([0])
zz=np.array([0])
vv=np.array([0])
gama=0.01
while gama<0.05:
    q=accuracy(gama)
    t=trade_time(gama)
    f=t*q
    zz=np.row_stack((zz, q))
    vv=np.row_stack((vv, t))
    z=np.row_stack((z, gama))
    v=np.row_stack((v, f))
   
    gama=gama+0.001

s=np.column_stack((z, zz,vv,v))
print(s)
    

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.00000000e-02 5.48990147e-01 4.08590000e+01 2.24311884e+01]
 [1.10000000e-02 5.47949883e-01 4.08110000e+01 2.23623827e+01]
 [1.20000000e-02 5.47736300e-01 4.07240000e+01 2.23060131e+01]
 [1.30000000e-02 5.49054694e-01 4.04100000e+01 2.21873002e+01]
 [1.40000000e-02 5.39913882e-01 3.96820000e+01 2.14248627e+01]
 [1.50000000e-02 5.46031470e-01 3.89660000e+01 2.12766623e+01]
 [1.60000000e-02 5.52691268e-01 3.81770000e+01 2.11000946e+01]
 [1.70000000e-02 5.51979696e-01 3.81530000e+01 2.10596813e+01]
 [1.80000000e-02 5.52298402e-01 3.82010000e+01 2.10983513e+01]
 [1.90000000e-02 5.52417133e-01 3.82440000e+01 2.11266408e+01]
 [2.00000000e-02 5.52639890e-01 3.81440000e+01 2.10798960e+01]
 [2.10000000e-02 5.63504871e-01 3.74720000e+01 2.11156545e+01]
 [2.20000000e-02 5.64252032e-01 3.74660000e+01 2.11402666e+01]
 [2.30000000e-02 5.63636518e-01 3.74230000e+01 2.10929694e+01]
 [2.40000000e-02 5.56264497e-01 3.69280000e+01 2.054173

In [6]:

def accuracy(gama):      
    u=0
    l=0
    while u<1000:

        SMB0=x[1:47,1]   
        SMB1=x[2:47,1]  #actual SMB1
        DSMB=x[1:47,8]
        E=np.array([0])
        F=np.array([0])

        for i in range(0,46):
            F0=float(SMB0[i])
            F0_grow=float(DSMB[i])
            Estimated_SMB=estimate_factor("RMW",F0,F0_grow)
            Estimated_direction=direction("RMW",F0,F0_grow)


            E=np.row_stack((E, [Estimated_SMB]))
            F=np.row_stack((F, [Estimated_direction]))
        #print("Estimated_SMB=",E[1:46,:])



        together=np.column_stack((E[1:46,:], SMB1,F[1:46,:],x[1:46,1]))
        #print(together)

        h=0
        hg=0
        for j in range(0,45):
            T=together[j][0]*together[j][1]
            TT=together[j][2]*together[j][3]
            if TT>0 or abs(together[j][0])>gama:
                hg=hg+1
                if T>0:
                    h=h+1

        accuracy=h/hg
        #print(accuracy)
        l=l+accuracy
        u=u+1

    mean_acciracy=l/1000

    return(mean_acciracy)

def trade_time(gama):      
    u=0
    l=0
    while u<1000:

        SMB0=x[1:47,1]   
        SMB1=x[2:47,1]  #actual SMB1
        DSMB=x[1:47,8]
        E=np.array([0])
        F=np.array([0])

        for i in range(0,46):
            F0=float(SMB0[i])
            F0_grow=float(DSMB[i])
            Estimated_SMB=estimate_factor("RMW",F0,F0_grow)
            Estimated_direction=direction("RMW",F0,F0_grow)


            E=np.row_stack((E, [Estimated_SMB]))
            F=np.row_stack((F, [Estimated_direction]))
        #print("Estimated_SMB=",E[1:46,:])



        together=np.column_stack((E[1:46,:], SMB1,F[1:46,:],x[1:46,1]))
        #print(together)

        h=0
        hg=0
        for j in range(0,45):
            T=together[j][0]*together[j][1]
            TT=together[j][2]*together[j][3]
            if TT>0 or abs(together[j][0])>gama:
                hg=hg+1
                if T>0:
                    h=h+1

        #accuracy=h/hg
        #print(accuracy)
        l=l+hg
        u=u+1

    mean_hg=l/1000

    return(mean_hg)

z=np.array([0])
v=np.array([0])
zz=np.array([0])
vv=np.array([0])
gama=0.01
while gama<0.09:
    q=accuracy(gama)
    t=trade_time(gama)
    f=t*q
    zz=np.row_stack((zz, q))
    vv=np.row_stack((vv, t))
    z=np.row_stack((z, gama))
    v=np.row_stack((v, f))
   
    gama=gama+0.001

s=np.column_stack((z, zz,vv,v))
print(s)
    

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.00000000e-02 5.47993227e-01 4.34730000e+01 2.38229095e+01]
 [1.10000000e-02 5.47574127e-01 4.34290000e+01 2.37805968e+01]
 [1.20000000e-02 5.48348728e-01 4.34640000e+01 2.38334291e+01]
 [1.30000000e-02 5.47411568e-01 4.34110000e+01 2.37636836e+01]
 [1.40000000e-02 5.49709419e-01 4.32880000e+01 2.37958213e+01]
 [1.50000000e-02 5.60115690e-01 4.24780000e+01 2.37925943e+01]
 [1.60000000e-02 5.64516817e-01 4.22220000e+01 2.38350291e+01]
 [1.70000000e-02 5.57095889e-01 4.12240000e+01 2.29657209e+01]
 [1.80000000e-02 5.48321102e-01 4.04590000e+01 2.21845235e+01]
 [1.90000000e-02 5.49299050e-01 3.87280000e+01 2.12732536e+01]
 [2.00000000e-02 5.49257285e-01 3.87180000e+01 2.12661435e+01]
 [2.10000000e-02 5.48170289e-01 3.85690000e+01 2.11423799e+01]
 [2.20000000e-02 5.40176243e-01 3.76470000e+01 2.03360150e+01]
 [2.30000000e-02 5.36244132e-01 3.73320000e+01 2.00190659e+01]
 [2.40000000e-02 5.48608240e-01 3.65180000e+01 2.003407